name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours (UTC)
  workflow_dispatch:        # Manual triggers

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write       # Required to push changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # External action

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3  # External action
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # External action
        with:
          target_branch: output
          build_dir: dist
          keep_files: false